CREATE TABLE listings (
    listing_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    seller_user_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    listing_status_id SMALLINT UNSIGNED NOT NULL,
    condition_id SMALLINT UNSIGNED NOT NULL,
    currency_code CHAR(3) NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT NOT NULL,
    price_amount DECIMAL(15, 0) NOT NULL,
    location_id BIGINT UNSIGNED NOT NULL,
    published_at DATETIME(3) NULL,
    expires_at DATETIME(3) NULL,
    archived_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (listing_id),
    CONSTRAINT chk_listings_price_nonnegative CHECK (price_amount >= 0),
    KEY ix_listings_category_price (category_id, price_amount),
    KEY ix_listings_newest (listing_status_id, published_at DESC, listing_id DESC),
    KEY ix_listings_seller_created (seller_user_id, created_at DESC),
    CONSTRAINT fk_listings_seller FOREIGN KEY (seller_user_id) REFERENCES users (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_listings_category FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_listings_status FOREIGN KEY (listing_status_id) REFERENCES listing_statuses (listing_status_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_listings_condition FOREIGN KEY (condition_id) REFERENCES conditions (condition_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_listings_currency FOREIGN KEY (currency_code) REFERENCES currencies (currency_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_listings_location FOREIGN KEY (location_id) REFERENCES locations (location_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FULLTEXT KEY ft_listings_search (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
